/// EVM stack depth tracking and validation
///
/// Validates that generated bytecode does not exceed the EVM stack limit (1024).
use std::collections::HashMap;

use crate::evm::CodegenError;
use crate::lowering::{LoweredBlock, LoweredCfg, LoweredInstruction, LoweredTerminator, StackSlot};
use merak_ir::ssa_ir::{BlockId, Terminator};

/// Maximum EVM stack depth (EVM specification).
pub const MAX_STACK_DEPTH: usize = 1024;

/// EVM stack depth occupied by the continuation address at every block
/// boundary (before pre-loading and after draining).
const CONTINUATION_DEPTH: usize = 1;

/// Stack depth information for a single function's CFG.
#[derive(Debug, Clone)]
pub struct StackDepthInfo {
    /// EVM stack depth at the entry of each basic block (after pre-loading).
    pub block_entry_depth: HashMap<BlockId, usize>,
    /// Maximum EVM stack depth reached anywhere during the function's execution.
    pub max_depth: usize,
}

/// Maximum number of extra EVM stack slots used **above the block-entry depth**
/// during the execution of a single `LoweredInstruction`.
///
/// Instructions that call `store_to_slot_vs` follow the pattern:
///   `(load operands) → compute → DUP1 → PUSH offset → MSTORE`
/// The peak is at the `PUSH offset` step, where the DUP'd copy and the offset
/// are both live simultaneously: `entry_depth + 1 (result) + 1 (DUP) + 1 (offset) = entry + 3`.
fn instruction_peak_transient(inst: &LoweredInstruction) -> usize {
    match inst {
        // Instructions that use store_to_slot_vs: DUP1 + PUSH_offset peaks at +3.
        LoweredInstruction::BinaryOp { .. }
        | LoweredInstruction::UnaryOp { .. }
        | LoweredInstruction::LoadConstant { .. }
        | LoweredInstruction::Copy { .. } => 3,

        // translate_storage_load: PUSH slot + SLOAD + PUSH offset + MSTORE.
        // Peak at PUSH offset step: entry + 2 (value on stack, offset being pushed).
        LoweredInstruction::StorageLoad { .. } => 2,

        // translate_storage_store: (DUP or PUSH+MLOAD) + PUSH slot + SSTORE.
        // Peak at PUSH slot step: entry + 2 (value + slot key simultaneously).
        LoweredInstruction::StorageStore { .. } => 2,

        // Call drains VS first (to CONTINUATION_DEPTH), then does its setup.
        // The relative transient above entry_depth is at most 2 (but absolute
        // peak = CONTINUATION_DEPTH + 2, handled separately in compute_block_peak_depth).
        LoweredInstruction::Call { .. } => 2,
    }
}

/// Maximum EVM depth reached by the terminator's control-flow opcodes,
/// measured **above `CONTINUATION_DEPTH`**.
///
/// Every terminator begins by draining the VS back to `CONTINUATION_DEPTH`
/// (emitting POPs or SWAP1+POP pairs), so these opcodes execute from a depth
/// of exactly `CONTINUATION_DEPTH = 1`.
fn terminator_peak_above_continuation(term: &LoweredTerminator) -> usize {
    match term {
        Terminator::Branch { .. } => 2, // worst case: standard path (PUSH+MLOAD + PUSH2)
        Terminator::Jump { .. } => 1,   // PUSH2 dest
        Terminator::Return { value: Some(_), .. } => 1, // PUSH+MLOAD or drain_except_tos
        Terminator::Return { value: None, .. } | Terminator::Unreachable => 0,
    }
}

/// Compute the maximum EVM stack depth reached **within** a single block's
/// execution, given that the block is entered with `entry_depth` items on the
/// EVM stack (= `CONTINUATION_DEPTH + layout.len()`).
///
/// - **Instructions**: `entry_depth + instruction_peak_transient(inst)`.
/// - **Terminator**: the terminator always drains to `CONTINUATION_DEPTH`
///   first, then emits its control-flow opcodes.  Its absolute peak is
///   therefore `CONTINUATION_DEPTH + terminator_peak_above_continuation(term)`.
///
/// Returns the maximum across both phases.
fn compute_block_peak_depth(block: &LoweredBlock, entry_depth: usize) -> usize {
    let inst_peak = block
        .instructions
        .iter()
        .map(|inst| entry_depth + instruction_peak_transient(inst))
        .max()
        .unwrap_or(entry_depth);

    // Terminators drain to continuation depth first; compute their absolute peak.
    let term_peak = CONTINUATION_DEPTH + terminator_peak_above_continuation(&block.terminator);

    inst_peak.max(term_peak)
}

/// Analyse EVM stack depth for a lowered function CFG.
///
/// For each basic block B the EVM stack entry depth is:
/// ```text
/// entry_depth(B) = CONTINUATION_DEPTH + entry_layout[B].len()
/// ```
///
/// The analysis:
/// 1. Computes `entry_depth(B)` for every block from its entry layout.
/// 2. Computes the peak EVM depth reached *within* each block using
///    `compute_block_peak_depth`.
/// 3. Returns `CodegenError` if any block's peak exceeds `MAX_STACK_DEPTH`.
///
/// # Errors
///
/// Returns `CodegenError::Other` if any block's transient peak exceeds
/// `MAX_STACK_DEPTH`.
pub fn analyze_stack_depth(
    cfg: &LoweredCfg,
    entry_layout: &HashMap<BlockId, Vec<StackSlot>>,
) -> Result<StackDepthInfo, CodegenError> {
    let mut block_entry_depth: HashMap<BlockId, usize> = HashMap::new();
    let mut max_depth = CONTINUATION_DEPTH;

    for (&block_id, block) in &cfg.blocks {
        // Entry depth = continuation (always present) + pre-loaded layout slots.
        let entry_depth = CONTINUATION_DEPTH + entry_layout.get(&block_id).map_or(0, |l| l.len());
        block_entry_depth.insert(block_id, entry_depth);

        let peak = compute_block_peak_depth(block, entry_depth);

        if peak > MAX_STACK_DEPTH {
            return Err(CodegenError::Other(format!(
                "EVM stack overflow: peak depth {} exceeds limit {} (block {})",
                peak, MAX_STACK_DEPTH, block_id
            )));
        }

        max_depth = max_depth.max(peak);
    }

    Ok(StackDepthInfo {
        block_entry_depth,
        max_depth,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lowering::{LoweredInstruction, StackSlot};
    use merak_ir::ssa_ir::{Constant, Operand, Terminator};

    #[test]
    fn terminator_peak_jump_is_one() {
        assert_eq!(
            terminator_peak_above_continuation(&Terminator::Jump { target: 0 }),
            1
        );
    }

    #[test]
    fn terminator_peak_branch_is_two() {
        let term = Terminator::Branch {
            condition: Operand::Constant(Constant::Bool(true)),
            then_block: 1,
            else_block: 2,
            meta: (),
        };
        assert_eq!(terminator_peak_above_continuation(&term), 2);
    }

    #[test]
    fn terminator_peak_return_value_is_one() {
        let term = Terminator::Return {
            value: Some(Operand::Location(StackSlot::new(0))),
            meta: (),
        };
        assert_eq!(terminator_peak_above_continuation(&term), 1);
    }

    #[test]
    fn terminator_peak_return_void_is_zero() {
        let term: LoweredTerminator = Terminator::Return {
            value: None,
            meta: (),
        };
        assert_eq!(terminator_peak_above_continuation(&term), 0);
    }

    #[test]
    fn terminator_peak_unreachable_is_zero() {
        assert_eq!(
            terminator_peak_above_continuation(&Terminator::Unreachable),
            0
        );
    }

    #[test]
    fn instruction_peak_binary_op_is_three() {
        use merak_ast::expression::BinaryOperator;
        let inst = LoweredInstruction::BinaryOp {
            dest: StackSlot::new(2),
            op: BinaryOperator::Add,
            left: Operand::Location(StackSlot::new(0)),
            right: Operand::Location(StackSlot::new(1)),
        };
        // store_to_slot_vs: DUP1 + PUSH offset peaks at entry + 3.
        assert_eq!(instruction_peak_transient(&inst), 3);
    }

    #[test]
    fn instruction_peak_load_constant_is_three() {
        let inst = LoweredInstruction::LoadConstant {
            dest: StackSlot::new(0),
            value: Constant::Int(42),
        };
        // store_to_slot_vs: DUP1 + PUSH offset peaks at entry + 3.
        assert_eq!(instruction_peak_transient(&inst), 3);
    }

    #[test]
    fn instruction_peak_copy_is_three() {
        let inst = LoweredInstruction::Copy {
            dest: StackSlot::new(1),
            source: Operand::Location(StackSlot::new(0)),
        };
        // store_to_slot_vs: DUP1 + PUSH offset peaks at entry + 3.
        assert_eq!(instruction_peak_transient(&inst), 3);
    }

    #[test]
    fn instruction_peak_storage_load_is_two() {
        let inst = LoweredInstruction::StorageLoad {
            dest: StackSlot::new(0),
            storage_slot: 0,
        };
        // translate_storage_load: PUSH slot + SLOAD + PUSH offset + MSTORE → peak +2.
        assert_eq!(instruction_peak_transient(&inst), 2);
    }

    #[test]
    fn instruction_peak_storage_store_is_two() {
        let inst = LoweredInstruction::StorageStore {
            storage_slot: 0,
            value: Operand::Location(StackSlot::new(0)),
        };
        // translate_storage_store: (DUP/MLOAD) + PUSH slot + SSTORE → peak +2.
        assert_eq!(instruction_peak_transient(&inst), 2);
    }

    #[test]
    fn block_peak_empty_instructions_uses_terminator() {
        // No instructions, only a Jump terminator.
        // term_peak = CONTINUATION_DEPTH + 1 = 1 + 1 = 2.
        // inst_peak = entry_depth = 1 (no instructions).
        // Expected peak = max(1, 2) = 2.
        let block = make_block_with_terminator(vec![], Terminator::Jump { target: 99 });
        assert_eq!(compute_block_peak_depth(&block, 1), 2);
    }

    #[test]
    fn block_peak_with_instruction_plus_jump() {
        // One BinaryOp (store_to_slot_vs transient +3) and a Jump terminator.
        // inst_peak = entry_depth(1) + 3 = 4.
        // term_peak = CONTINUATION_DEPTH(1) + 1 = 2.
        // Expected peak = max(4, 2) = 4.
        use merak_ast::expression::BinaryOperator;
        let inst = LoweredInstruction::BinaryOp {
            dest: StackSlot::new(2),
            op: BinaryOperator::Add,
            left: Operand::Location(StackSlot::new(0)),
            right: Operand::Location(StackSlot::new(1)),
        };
        let block = make_block_with_terminator(vec![inst], Terminator::Jump { target: 99 });
        assert_eq!(compute_block_peak_depth(&block, 1), 4);
    }

    #[test]
    fn block_peak_return_void_is_base() {
        // Empty instructions, void Return (terminator peak above continuation = 0).
        // inst_peak = entry_depth = 1 (no instructions).
        // term_peak = CONTINUATION_DEPTH + 0 = 1.
        // Expected peak = max(1, 1) = 1.
        let block = make_block_with_terminator(
            vec![],
            Terminator::Return {
                value: None,
                meta: (),
            },
        );
        assert_eq!(compute_block_peak_depth(&block, 1), 1);
    }

    #[test]
    fn block_peak_with_layout_slots_increases_entry_depth() {
        // entry_depth = 1 (continuation) + 3 (layout slots) = 4.
        // One BinaryOp: inst_peak = 4 + 3 = 7.
        // Jump terminator: term_peak = 1 + 1 = 2.
        // Expected peak = max(7, 2) = 7.
        use merak_ast::expression::BinaryOperator;
        let inst = LoweredInstruction::BinaryOp {
            dest: StackSlot::new(3),
            op: BinaryOperator::Add,
            left: Operand::Location(StackSlot::new(0)),
            right: Operand::Location(StackSlot::new(1)),
        };
        let block = make_block_with_terminator(vec![inst], Terminator::Jump { target: 99 });
        assert_eq!(compute_block_peak_depth(&block, 4), 7);
    }

    /// Build a minimal `LoweredBlock` with the given instructions and terminator.
    fn make_block_with_terminator(
        instructions: Vec<LoweredInstruction>,
        terminator: LoweredTerminator,
    ) -> LoweredBlock {
        use merak_ir::BasicBlock;
        BasicBlock {
            id: 0,
            instructions,
            terminator,
            predecessors: vec![],
            successors: vec![],
            loop_invariants: None,
            loop_variants: None,
        }
    }
}
