use super::opcodes::Opcode;
use std::collections::HashMap;

/// Label identifier for jump targets
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Label(pub usize);

impl Label {
    pub fn new(id: usize) -> Self {
        Label(id)
    }
}

/// Pending jump that needs label resolution
#[derive(Debug, Clone)]
struct PendingJump {
    /// Position in bytecode where the jump address starts
    position: usize,
    /// Target label
    target: Label,
    /// Size of the address field (in bytes)
    size: usize,
}

/// Builder for EVM bytecode with label resolution
pub struct BytecodeBuilder {
    /// Generated bytecode
    code: Vec<u8>,
    /// Resolved label positions
    labels: HashMap<Label, usize>,
    /// Pending jumps awaiting label resolution
    pending_jumps: Vec<PendingJump>,
    /// Next label ID
    next_label_id: usize,
    /// Current stack depth (for validation, optional)
    #[allow(dead_code)]
    stack_depth: usize,
    /// Byte offset where the runtime section begins (if set).
    ///
    /// Any pending jump whose *source position* AND *resolved target* are both
    /// ≥ this value will have the runtime-start subtracted from its address.
    /// This is necessary because the runtime section is extracted via CODECOPY
    /// and stored at address 0 in the deployed contract, so all intra-runtime
    /// jump targets must be relative to the start of the runtime section.
    runtime_start: Option<usize>,
}

impl BytecodeBuilder {
    /// Create a new bytecode builder
    pub fn new() -> Self {
        Self {
            code: Vec::new(),
            labels: HashMap::new(),
            pending_jumps: Vec::new(),
            next_label_id: 0,
            stack_depth: 0,
            runtime_start: None,
        }
    }

    /// Mark the current position as the start of the runtime section.
    ///
    /// Must be called exactly once, after the deploy section has been emitted
    /// and before any runtime-section code is emitted.
    pub fn mark_runtime_start(&mut self) {
        self.runtime_start = Some(self.code.len());
    }

    /// Get current bytecode position
    pub fn position(&self) -> usize {
        self.code.len()
    }

    /// Create a new label
    pub fn new_label(&mut self) -> Label {
        let label = Label(self.next_label_id);
        self.next_label_id += 1;
        label
    }

    /// Mark current position with a label
    pub fn mark_label(&mut self, label: Label) {
        let pos = self.code.len();
        self.labels.insert(label, pos);
    }

    /// Emit a single opcode
    pub fn emit(&mut self, opcode: Opcode) {
        self.code.push(opcode.encode());
    }

    /// Emit raw bytes
    pub fn emit_bytes(&mut self, bytes: &[u8]) {
        self.code.extend_from_slice(bytes);
    }

    /// Push a value onto the stack (selects appropriate PUSHn opcode)
    pub fn push(&mut self, value: &[u8]) {
        // Remove leading zeros
        let trimmed = trim_leading_zeros(value);

        if trimmed.is_empty() {
            // Push 0
            self.emit(Opcode::PUSH1);
            self.code.push(0);
        } else {
            let size = trimmed.len();
            if let Some(push_op) = Opcode::push_for_size(size) {
                self.emit(push_op);
                self.code.extend_from_slice(trimmed);
            } else {
                panic!("Cannot push value larger than 32 bytes: {} bytes", size);
            }
        }
    }

    /// Push a u64 value
    pub fn push_u64(&mut self, value: u64) {
        let bytes = value.to_be_bytes();
        self.push(&bytes);
    }

    /// Push a u256 value (big-endian bytes)
    pub fn push_u256(&mut self, bytes: &[u8; 32]) {
        self.push(bytes);
    }

    /// Push a label address onto the stack (unresolved, will be patched later).
    ///
    /// Emits `PUSH2 <placeholder>` and records a pending jump for label resolution.
    /// Unlike `jump_to`, does NOT emit a JUMP opcode — the address stays on the stack.
    /// Used to push a continuation address before calling `jump_to` for the callee.
    pub fn push_label(&mut self, label: Label) {
        let position = self.code.len();
        self.emit(Opcode::PUSH2);
        self.code.push(0xFF); // Placeholder high byte
        self.code.push(0xFF); // Placeholder low byte
        self.pending_jumps.push(PendingJump {
            position: position + 1,
            target: label,
            size: 2,
        });
    }

    /// Emit a jump to a label (unresolved, will be patched later)
    pub fn jump_to(&mut self, label: Label) {
        // Reserve space for PUSH2 + address (3 bytes total)
        // We use PUSH2 assuming max bytecode size < 64KB
        // TODO: Support larger bytecode with PUSH3/PUSH4
        let position = self.code.len();
        self.emit(Opcode::PUSH2);
        self.code.push(0xFF); // Placeholder
        self.code.push(0xFF); // Placeholder

        self.pending_jumps.push(PendingJump {
            position: position + 1, // Position after PUSH2 opcode
            target: label,
            size: 2,
        });

        self.emit(Opcode::JUMP);
    }

    /// Emit a conditional jump to a label (unresolved)
    /// Expects condition to be on top of stack
    pub fn jumpi_to(&mut self, label: Label) {
        // Reserve space for PUSH2 + address (3 bytes total)
        let position = self.code.len();
        self.emit(Opcode::PUSH2);
        self.code.push(0xFF); // Placeholder
        self.code.push(0xFF); // Placeholder

        self.pending_jumps.push(PendingJump {
            position: position + 1,
            target: label,
            size: 2,
        });

        self.emit(Opcode::JUMPI);
    }

    /// Finalize bytecode by resolving all label references.
    ///
    /// If [`mark_runtime_start`] was called, any jump whose source position
    /// **and** target are both inside the runtime section has `runtime_start`
    /// subtracted from the patched address.  This makes intra-runtime jumps
    /// 0-relative so they are correct after the runtime section is extracted
    /// by CODECOPY and stored as the deployed contract code.
    pub fn finalize(mut self) -> Result<Vec<u8>, CodegenError> {
        for jump in &self.pending_jumps {
            let target_pos = self
                .labels
                .get(&jump.target)
                .ok_or_else(|| CodegenError::UnresolvedLabel(jump.target))?;

            // If both the PUSH2 and its target are inside the runtime section,
            // adjust the address to be relative to runtime_start so it is
            // correct in the 0-indexed deployed bytecode.
            let effective_target = match self.runtime_start {
                Some(rs) if jump.position >= rs && *target_pos >= rs => target_pos - rs,
                _ => *target_pos,
            };

            match jump.size {
                2 => {
                    let bytes = (effective_target as u16).to_be_bytes();
                    self.code[jump.position] = bytes[0];
                    self.code[jump.position + 1] = bytes[1];
                }
                _ => {
                    return Err(CodegenError::UnsupportedJumpSize(jump.size));
                }
            }
        }

        Ok(self.code)
    }

    /// Get current bytecode (before finalization)
    pub fn code(&self) -> &[u8] {
        &self.code
    }
}

impl Default for BytecodeBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Remove leading zero bytes from a slice
fn trim_leading_zeros(bytes: &[u8]) -> &[u8] {
    let mut start = 0;
    while start < bytes.len() && bytes[start] == 0 {
        start += 1;
    }
    &bytes[start..]
}

/// Codegen errors
#[derive(Debug, Clone, PartialEq)]
pub enum CodegenError {
    /// Instruction is verification-only and doesn't generate code
    VerificationOnly,
    /// Label was referenced but never defined
    UnresolvedLabel(Label),
    /// Jump size not supported
    UnsupportedJumpSize(usize),
    /// Stack overflow (exceeds EVM limit of 1024)
    StackOverflow,
    /// Stack underflow
    StackUnderflow,
    /// Invalid instruction
    InvalidInstruction(String),
    /// Other errors
    Other(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::VerificationOnly => {
                write!(f, "Verification-only instruction (no code generation)")
            }
            CodegenError::UnresolvedLabel(label) => {
                write!(f, "Unresolved label: {:?}", label)
            }
            CodegenError::UnsupportedJumpSize(size) => {
                write!(f, "Unsupported jump size: {} bytes", size)
            }
            CodegenError::StackOverflow => {
                write!(f, "Stack overflow (exceeds 1024 limit)")
            }
            CodegenError::StackUnderflow => {
                write!(f, "Stack underflow")
            }
            CodegenError::InvalidInstruction(msg) => {
                write!(f, "Invalid instruction: {}", msg)
            }
            CodegenError::Other(msg) => write!(f, "{}", msg),
        }
    }
}

impl std::error::Error for CodegenError {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_simple_bytecode() {
        let mut builder = BytecodeBuilder::new();
        builder.push(&[0x01]); // PUSH1 0x01
        builder.push(&[0x02]); // PUSH1 0x02
        builder.emit(Opcode::ADD); // ADD

        let bytecode = builder.finalize().unwrap();
        assert_eq!(bytecode, vec![0x60, 0x01, 0x60, 0x02, 0x01]);
    }

    #[test]
    fn test_label_resolution() {
        let mut builder = BytecodeBuilder::new();

        let target = builder.new_label();

        // Jump to label
        builder.jump_to(target);

        // Some code
        builder.emit(Opcode::PUSH1);
        builder.code.push(0x00);

        // Mark the label
        builder.mark_label(target);
        builder.emit(Opcode::JUMPDEST);
        builder.emit(Opcode::STOP);

        let bytecode = builder.finalize().unwrap();

        // Verify jump points to JUMPDEST
        // PUSH2 <addr> JUMP PUSH1 0x00 JUMPDEST STOP
        // 0x61 <hi> <lo> 0x56 0x60 0x00 0x5b 0x00
        assert_eq!(bytecode[0], 0x61); // PUSH2
        let jump_addr = u16::from_be_bytes([bytecode[1], bytecode[2]]);
        assert_eq!(jump_addr as usize, 6); // Points to JUMPDEST at position 6
    }

    #[test]
    fn test_push_trimming() {
        let mut builder = BytecodeBuilder::new();

        // Push with leading zeros
        builder.push(&[0x00, 0x00, 0x42]);

        let bytecode = builder.finalize().unwrap();
        // Should emit PUSH1 0x42, not PUSH3
        assert_eq!(bytecode, vec![0x60, 0x42]);
    }

    #[test]
    fn test_unresolved_label_error() {
        let mut builder = BytecodeBuilder::new();
        let label = builder.new_label();

        // Jump to label without marking it
        builder.jump_to(label);

        // Should fail to finalize
        let result = builder.finalize();
        assert!(matches!(result, Err(CodegenError::UnresolvedLabel(_))));
    }

    #[test]
    fn test_push_zero() {
        let mut builder = BytecodeBuilder::new();
        builder.push(&[0x00, 0x00, 0x00]);

        let bytecode = builder.finalize().unwrap();
        // Should emit PUSH1 0x00
        assert_eq!(bytecode, vec![0x60, 0x00]);
    }

    #[test]
    fn test_push_u64() {
        let mut builder = BytecodeBuilder::new();
        builder.push_u64(0x123456);

        let bytecode = builder.finalize().unwrap();
        // Should emit PUSH3 0x123456
        assert_eq!(bytecode, vec![0x62, 0x12, 0x34, 0x56]);
    }
}
